#!/usr/bin/env bash
# Write ~/.config/ai-brain/env and (Intel/Fedora) ~/start-ai-brain.sh.
# Never rewrites Apple live scripts. Do not write mcp.json keys.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

HOST=""
VAULT=""
YES=0
FORCE=0

usage() {
  cat <<EOF
Usage: install-ai-brain.sh --host=travis-fedora|travis-mac-intel|travis-mac-apple [options]

Options:
  --host=NAME     travis-fedora | travis-mac-intel | travis-mac-apple
  --vault=PATH    LiveSync vault root (required for intel/fedora)
  --yes           Confirm running a host installer that does not match this OS
  --force         Overwrite ~/.config/ai-brain/env; Apple still refuses start-symlink
  -h, --help

Travis-Fedora example:
  ./scripts/install-ai-brain.sh --host=travis-fedora \\
    --vault "/home/travis/Obsidian/obsidian-work/obsidian-work"
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --host=*) HOST="${1#--host=}"; shift ;;
    --host) HOST="${2:-}"; shift 2 ;;
    --vault=*) VAULT="${1#--vault=}"; shift ;;
    --vault) VAULT="${2:-}"; shift 2 ;;
    --yes) YES=1; shift ;;
    --force) FORCE=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ -z "$HOST" ]]; then
  echo "FAIL: --host is required" >&2
  usage >&2
  exit 1
fi

write_env() {
  local log_dir machine_label
  machine_label="$HOST"
  if [[ "$HOST" == "travis-fedora" ]]; then
    log_dir="${HOME}/.local/state/ai-brain"
  else
    log_dir="${HOME}/Library/Logs"
  fi
  mkdir -p "${HOME}/.config/ai-brain" "$log_dir"
  cat >"${HOME}/.config/ai-brain/env" <<EOF
# Generated by install-ai-brain.sh — do not copy another machine's file.
AI_BRAIN_HOST=${HOST}
MACHINE_LABEL=${machine_label}
VAULT_DIR=${VAULT}
OBSIDIAN_VAULT_DIR=${VAULT}
MY_AI_BRAIN_REPO=${HOME}/Github/my_ai_brain
AGENTIC_OS_REPO=${HOME}/Github/agentic-os-dashboard
LOG_DIR=${log_dir}
OLLAMA_URL=http://127.0.0.1:11434
SUPABASE_URL=http://127.0.0.1:54321
OLLAMA_EMBED_MODEL=nomic-embed-text
EOF
  chmod 600 "${HOME}/.config/ai-brain/env"
  echo "Wrote ${HOME}/.config/ai-brain/env (mode 600)"
}

vault_looks_ok() {
  [[ -d "$VAULT" ]] || return 1
  [[ -f "${VAULT}/hot.md" || -f "${VAULT}/AI Brain/hot.md" ]]
}

if [[ "$HOST" == "travis-mac-apple" ]]; then
  if [[ "$FORCE" -ne 1 ]]; then
    echo "Apple stack is frozen; use brain-sync.sh manually." >&2
    echo "To write ~/.config/ai-brain/env only, re-run with --force --vault \"<apple vault>\"." >&2
    exit 1
  fi
  if [[ -z "$VAULT" ]]; then
    echo "FAIL: --vault is required even for Apple env-only" >&2
    exit 1
  fi
  vault_looks_ok || { echo "FAIL: vault missing hot.md: ${VAULT}" >&2; exit 1; }
  write_env
  mkdir -p "${VAULT}/open-brain-sync"
  echo "Apple stack is frozen; use brain-sync.sh manually."
  echo "Did not change ~/start-ai-brain.sh or ~/.cursor/hooks.json."
  exit 0
fi

if [[ "$HOST" == "travis-mac-intel" ]]; then
  echo "FAIL: Travis-Mac-Intel scripts are not in this Fedora-first drop." >&2
  echo "Use --host=travis-fedora on the Fedora machine." >&2
  exit 1
fi

if [[ "$HOST" != "travis-fedora" ]]; then
  echo "FAIL: unknown --host=${HOST}" >&2
  exit 1
fi

if [[ "$(uname -s)" == "Darwin" && "$YES" -ne 1 ]]; then
  echo "FAIL: this looks like macOS. Do not install Travis-Fedora here." >&2
  echo "Pass --yes only if you really intend to write Fedora env files on this Mac." >&2
  exit 1
fi

if [[ "$(uname -m)" == "arm64" && "$(uname -s)" == "Darwin" && "$YES" -ne 1 ]]; then
  echo "FAIL: Apple Silicon detected. Refusing Fedora install without --yes." >&2
  exit 1
fi

if [[ -z "$VAULT" ]]; then
  echo "FAIL: --vault is required for Travis-Fedora" >&2
  echo "Example: --vault \"/home/travis/Obsidian/obsidian-work/obsidian-work\"" >&2
  exit 1
fi

case "$VAULT" in
  *"Agentic OS Dashboard"|*"Agentic OS Dashboard/")
    echo "FAIL: that path is a folder inside the vault, not the vault root." >&2
    echo "Use: /home/travis/Obsidian/obsidian-work/obsidian-work" >&2
    echo "Mac equivalent root: /Users/travis/Documents/MBP-M3-RH/Obsidian-Work-Vault/Obsidian-Work" >&2
    exit 1
    ;;
esac

if ! vault_looks_ok; then
  echo "FAIL: vault must be a directory containing hot.md or AI Brain/hot.md" >&2
  echo "  got: ${VAULT}" >&2
  exit 1
fi

if [[ -e "${HOME}/start-ai-brain.sh" || -L "${HOME}/start-ai-brain.sh" ]]; then
  current="$(readlink "${HOME}/start-ai-brain.sh" 2>/dev/null || true)"
  if [[ "$current" == *"/start-ai-brain.sh" && "$current" != *travis-fedora* && "$FORCE" -ne 1 ]]; then
    echo "FAIL: ~/start-ai-brain.sh already exists (${current}). Pass --force to replace with Fedora start." >&2
    exit 1
  fi
fi

write_env
mkdir -p "${VAULT}/open-brain-sync"

start_script="${SCRIPT_DIR}/start-ai-brain-travis-fedora.sh"
chmod +x "$start_script" \
  "${SCRIPT_DIR}/ensure-ai-brain-services-travis-fedora.sh" \
  "${SCRIPT_DIR}/cursor-hook-ensure-services-travis-fedora.sh" \
  "${SCRIPT_DIR}/verify-travis-fedora.sh" \
  "${SCRIPT_DIR}/brain-sync.sh" \
  2>/dev/null || true

ln -sf "$start_script" "${HOME}/start-ai-brain.sh"
echo "Symlinked ${HOME}/start-ai-brain.sh → ${start_script}"

if [[ -d "${REPO_ROOT}/mcp-server" ]]; then
  (cd "${REPO_ROOT}/mcp-server" && npm install)
fi

cat <<EOF

Next (Travis-Fedora):

  1. First-time Open Brain (if ollama/supabase containers do not exist yet):
     See ${REPO_ROOT}/docs/hosts/TRAVIS-FEDORA.md

  2. Dashboard Cursor bridge (this machine's vault, this machine's keys):
     cd \$HOME/Github/agentic-os-dashboard
     ./scripts/setup-cursor-bridge.sh --vault "${VAULT}" --memory-backend open-brain --brain-read-gate

  3. Dashboard container (SELinux :z is in run-container.sh):
     ./run-container-travis-fedora.sh

  4. Point ~/.cursor/hooks.json sessionStart at:
     ${SCRIPT_DIR}/cursor-hook-ensure-services-travis-fedora.sh

  5. Reload Cursor, then:
     ~/start-ai-brain.sh
     ${SCRIPT_DIR}/verify-travis-fedora.sh
     ./scripts/health-check-travis-fedora.sh --quick   # from agentic-os-dashboard

  6. After LiveSync has Apple's open-brain-sync/thoughts.json (non-zero):
     ${SCRIPT_DIR}/brain-sync.sh pull
     ${SCRIPT_DIR}/brain-sync.sh status

Do not copy Apple's SUPABASE_SERVICE_ROLE_KEY. Do not run Apple ensure/start scripts here.
EOF
